version: '3.9'
services:
  es:
    image: registry.cn-beijing.aliyuncs.com/env_halfcoke/elasticsearch:7.11.1
    container_name: es
    environment:
      - node.name=es
      - cluster.name=es-docker-cluster
      - cluster.initial_master_nodes=es
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es_data:/usr/share/elasticsearch/data
      - type: volume
        source: es_conf
        target: /usr/share/elasticsearch/config
    ports:
      - 9200:9200
    networks:
      - dblpweb

  dblp_data_process:
    image: registry.cn-beijing.aliyuncs.com/env_halfcoke/dblp-data-process:1.0.0
    container_name: dblp_data_process
    command:
      - "python"
      - "main.py"
    depends_on:
      - "es"
    volumes:
      - type: volume
        source: dblpweblog
        target: /var/log
      - type: volume
        source: dblpwebconf
        target: /opt/dblpDataProcess/conf
      - type: volume
        source: dblpdata
        target: /opt/dblpDataProcess/resources
    networks:
      - dblpweb

  dblp_web_backend:
    image: registry.cn-beijing.aliyuncs.com/env_halfcoke/dblp-web-backend:2.0.0
    container_name: dblp_web_backend
    depends_on:
      - "es"
    ports:
      - 5051:5051
    volumes:
      - type: volume
        source: dblpweblog
        target: /var/log
      - type: volume
        source: dblpwebconf
        target: /opt/dblpWebBackend/conf
    networks:
      - dblpweb

  webserver:
    image: nginx:1.19.7-alpine
    container_name: webserver
    depends_on:
      - "es"
      - "dblp_web_backend"
    volumes:
      - type: volume
        source: nginx_conf
        target: /etc/nginx
      - type: volume
        source: html
        target: /usr/share/nginx/html
    ports:
      - 80:80
      - 443:443
    networks:
      - dblpweb

volumes:
  dblpweblog:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/opt/dblpweb/logs'
  dblpwebconf:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/opt/dblpweb/conf'
  dblpdata:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/opt/dblpweb/data'
  nginx_conf:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/opt/nginx/conf'
  html:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/opt/dblpweb/searchwebui/dist'
  es_data:
    driver: local
  es_conf:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/opt/elasticsearch/conf'
networks:
  dblpweb:
    driver: bridge